[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
verifier = "FyxYE2zo4NzYuQKiXiVfEFfVMHm69RNz4gwKNqws66VL"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec vitest run -c tests/vitest.config.ts"

[hooks]
