// Reshape unit tests. Fixtures are generated by gen.mjs (ffjavascript LE+reverse path) — a different
// code path from reshape.ts (native BigInt) — so a shared bug between the two surfaces as a test failure.
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  canonicalVkHash,
  reshapeProof,
  reshapePublicInputs,
  reshapeVk,
  type SnarkjsProof,
  type SnarkjsVk,
} from "../src/reshape.js";

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), "fixtures");

interface ExpectedFixture {
  vkCanonicalHex: string;
  vkHashHex: string;
  proofCanonicalHex: string;
  publicInputsHex: string[];
}

// Frozen fixtures, not live circuits/<c>/*.json — setup.sh's phase-2 entropy varies per run,
// so live VKs change every regen. Frozen copies pin the input → expected-output relationship.
function loadFixture(circuit: string) {
  const base = join(fixturesDir, circuit);
  const vk = JSON.parse(readFileSync(join(base, "vk.json"), "utf8")) as SnarkjsVk;
  const proof = JSON.parse(
    readFileSync(join(base, "proof.json"), "utf8"),
  ) as SnarkjsProof;
  const pub = JSON.parse(readFileSync(join(base, "public.json"), "utf8")) as string[];
  const expected = JSON.parse(
    readFileSync(join(base, "expected.json"), "utf8"),
  ) as ExpectedFixture; // produced by gen.mjs's independent reshape; never hand-edited
  return { vk, proof, pub, expected };
}

function hex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("hex");
}

// Both circuits because they have different public-input arity (1 vs 2); reshape must handle both shapes.
describe.each(["preimage", "range"])("reshape %s circuit", (circuit) => {
  const { vk, proof, pub, expected } = loadFixture(circuit);

  it("VK canonical bytes match independent fixture", () => {
    const actual = reshapeVk(vk);
    expect(hex(actual)).toBe(expected.vkCanonicalHex);
  });

  it("canonicalVkHash matches fixture sha256", () => {
    const hash = canonicalVkHash(reshapeVk(vk));
    expect(hex(hash)).toBe(expected.vkHashHex);
  });

  it("proof canonical bytes match independent fixture", () => {
    const actual = reshapeProof(proof);
    expect(actual).toHaveLength(256);
    expect(hex(actual)).toBe(expected.proofCanonicalHex);
  });

  it("public inputs map to 32-byte BE", () => {
    const actual = reshapePublicInputs(pub);
    expect(actual).toHaveLength(expected.publicInputsHex.length);
    for (let i = 0; i < actual.length; i++) {
      expect(actual[i]).toHaveLength(32);
      expect(hex(actual[i]!)).toBe(expected.publicInputsHex[i]);
    }
  });
});

// Structural assertions derived from first principles — catches shared bugs between
// reshape.ts and gen.mjs that would still pass the byte-equality tests above.
describe("canonical VK layout invariants", () => {
  const { vk } = loadFixture("preimage");
  const bytes = reshapeVk(vk);

  it("fixed prefix is 452 bytes (alpha_g1 + 3 G2 + u32 len)", () => {
    expect(bytes.length).toBe(452 + vk.IC.length * 64);
  });

  it("ic_len prefix at offset 448 is little-endian", () => {
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    expect(view.getUint32(448, true)).toBe(vk.IC.length);
  });
});
